### ISSUE TITLE
RNN function: not all input parameters are described

### ISSUE THREAD

**Issue by ustiugov** [kmu-bigdata/serverless-faas-workbench#1]
Dear authors,

Thank you very much for this suite. 

Could you please describe some of the input parameters for the [rnn function](https://github.com/kmu-bigdata/serverless-faas-workbench/wiki/generating-names-rnn)?
Namely, all_categories, n_categories, all_letters and n_letters. I would really appreciate if you could let me know their values in a typical scenario.

Thank you in advance!

**Comment by kmu-leeky** [comment]
@KimJeongChul  Can you please elaborate the input parameters? Regarding the practicality of this scenario, AFAIK, it was very tough to make a more realistic RNN scenario to run on top of Lambda. I believe it was the minimal overhead RNN that we could execute on Lambda.

**Comment by KimJeongChul** [comment]
Hi @ustiugov 

The [rnn_generate_character_level](https://github.com/kmu-bigdata/serverless-faas-workbench/blob/master/aws/cpu-memory/model_serving/rnn_generate_character_level/lambda_function.py) 
lambda function need parameters(language, start_letters, model_parameter_object_key, model_object_key, model_bucket) to classify names into their language of origin.
 - language : language of origin 
 - start_letters: starting letters of name
 - model_parameter_object_key: pre-trained rnn model parameter(rnn_params.pkl)
 - model_object_key: entire model [Pytorch - Recommended approach for saving a model](https://github.com/pytorch/pytorch/blob/761d6799beb3afa03657a71776412a2171ee7533/docs/source/notes/serialization.rst)
 - model_bucket: s3 bucket name

Next, the rnn model parameter(rnn_params.pkl) has all_categories, n_categories, all_letters and n_letters.
 - all_categories: 'French', 'Czech', 'Dutch', 'Polish', 'Scottish', 'Chinese', 'English', 'Italian', 'Portuguese', 'Japanese', 'German', 'Russian', 'Korean', 'Arabic', 'Greek', 'Vietnamese', 'Spanish', 'Irish'
 - n_categories: length of all_categories = 18
 - all_letters: **abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ .,;'-**
 - n_letters: 59
```python
all_letters = string.ascii_letters + " .,;'-"
n_letters = len(all_letters) + 1
```

I hope I can be of some help. If you have any questions, I will recommend referring in Pytorch Tutorial.
Reference : https://pytorch.org/tutorials/intermediate/char_rnn_generation_tutorial.html

**Comment by ustiugov** [comment]
Thank you for the prompt response. I would appreciate if you could add this info to the corresponding WIki page. 

Also, there is a typo in rnn.py:
https://github.com/kmu-bigdata/serverless-faas-workbench/blob/e4473fa0bc515b7ac6ec74cf8428980a944810fb/aws/cpu-memory/model_serving/rnn_generate_character_level/rnn.py#L52

The correct function reference would be: `gen_category_tensor'.  I am going to submit a PR to fix it.

**Comment by KimJeongChul** [comment]
Dear @ustiugov
Thank you for refactoring code.
Have good day!
